In [1]:
# imPORT LIBRARIES 
import numpy as np
import matplotlib.pyplot as plt
from scipy.interpolate import interp1d
from math import pi, sqrt
import handcalcs.render
import pandas as pd
import json 
# !pip install handcalcs

In [2]:
# CONFIGURATIONS
#help(handcalcs.set_option)
handcalcs.set_option("latex_block_start", "$")
handcalcs.set_option("latex_block_end", "$")
handcalcs.set_option("math_environment_end", "aligned")
handcalcs.set_option("use_scientific_notation",True)
#handcalcs.set_option("line_break", "\\\\[20pt]")
#handcalcs.set_option("param_columns", 1)

#handcalcs.set_option("math_environment_start", "aligned")
#handcalcs.set_option("math_environment_end", "aligned")
#handcalcs.set_option("line_break", r"<br>")
#handcalcs.set_option("line_break", r"\\")

In [3]:
from localcode import *
fig_counter=1

# Design of Magnetic Cores Lm and Lr

## Inputs and claculated parameters

In [4]:
with open("../01_llc_tank/04_outputs/out_results.json", "r", encoding="utf-8") as f:
    out_datas = json.load(f)

# Load variables 
for key, value in out_datas.items():
    globals()[key] = value
    
params = ['n',  'Lm_uH', 'fsw_min', 'fsw_max', 'Ir_rms', 'Im_rms', 'Ioe_rms', 'Ios_rms', 'L_second_uH']

dic_transfo= {x:out_datas[x] for x in params}
Al = out_datas["Lm_uH"]/out_datas["n"]**2
dic_transfo["Al_uH"]= Al

S= pd.Series(dic_transfo, name = "Transormer parameters").to_frame()
display(S)

             Transormer parameters
n                            4.000
Lm_uH                       65.392
fsw_min                  60170.000
fsw_max                 156220.000
Ir_rms                      10.354
Im_rms                       6.992
Ioe_rms                      7.636
Ios_rms                     30.545
L_second_uH                  4.087
Al_uH                        4.087

In [5]:
with open("../01_llc_tank/04_outputs/inp_datas.json", "r", encoding="utf-8") as f:
    inp_datas = json.load(f)



# Load variables 
for key, value in inp_datas.items():
    globals()[key] = value

## Transformer design

In [6]:
with open("../01_llc_tank/04_outputs/out_results.json", "r", encoding="utf-8") as f:
    out_datas = json.load(f)


# Load variables 
for key, value in out_datas.items():
    globals()[key] = value
    
params = ['n',  'Lm_uH', 'fsw_min', 'fsw_max', 'Ir_rms', 'Im_rms', 'Ioe_rms', 'Ios_rms', 'L_second_uH']

dic_transfo= {x:out_datas[x] for x in params}
Al = out_datas["Lm_uH"]/out_datas["n"]**2
dic_transfo["Al_uH"]= Al

S= pd.Series(dic_transfo, name = "Transormer parameters").to_frame()
display(S)

             Transormer parameters
n                            4.000
Lm_uH                       65.392
fsw_min                  60170.000
fsw_max                 156220.000
Ir_rms                      10.354
Im_rms                       6.992
Ioe_rms                      7.636
Ios_rms                     30.545
L_second_uH                  4.087
Al_uH                        4.087

where: 
* $n$: Transformer turns ratio $ n = N_p / N_s $
* $N_p = n$ since $N_s= 1$
* $Lm_uH$: Magnetizing inductance $ L_m $, sets magnetizing current and contributes to gain shaping
* $fsw_min$: Minimum switching frequency $ f_{sw,\min} $, corresponds to maximum load
* $fsw_max$: Maximum switching frequency $ f_{sw,\max} $, corresponds to no-load
* $Ir_rms$: RMS current in the resonant tank inductor $ I_r = \sqrt{I_m^2 + I_{oe}^2} $
* $Im_rms$: RMS magnetizing current $ I_m $, flows through $ L_m $
* $Ioe_rms$: RMS transferred current in the primary winding, represents reflected load current
* $Ios_rms$: RMS current in the secondary winding $ I_{os} = I_{oe} \cdot n $
* $Al_uH$: Inductance per turn squared $ A_L $, used to compute turns: $ L = A_L \cdot N^2 $

**Bpeak formula**

$$
B_{peak} = \frac{L_m \cdot Im_{peak}}{N_p \cdot A_e}= \frac{L_m \cdot \sqrt{2} \cdot  Im_{rms}}{N_p \cdot A_{emin}}
$$

Where
- `A_e` = effective core area (in m²)
- `A_emin` = effective minimum core area (in m²)
- `N_p` = primary turnes

The `Al` value:

In [7]:
%%render long
Al_nH= 1e3*Lm_uH/n**2 # nH/turn squared

**ELP 43/10/28 core**

In [8]:
%%render long
Lm_uH
Np= n # turns 
Ae = 225 # mm2 see datasheet ELP 43/10/28
Aemin = 217 # mm2 see datasheet ELP 43/10/28
Im_rms # Arms
B_peak = 1e3*Lm*sqrt(2)*Im_rms/(Np*Aemin*1e-6) # mT > Bs= 250mT NOK

Since the formulat of peak flux density is $
\begin{aligned}
B_{peak} = \mathrm{Lm} \cdot \sqrt { 2 } \cdot \frac{ \mathrm{Im}_{rms} }{ \mathrm{Np} \cdot \mathrm{Aemin} }   
\end{aligned}
$
We can reduct the peak by reducing the current or by reducing Lm or by increasing Np

We can reduce $A_L$ by adding an air gap, below the formula of air gap length

$$
A_{L}' = \frac{A_L}{1 + \mu_r \,\frac{L_g}{L_e}}
$$

$$
l_g = \frac{L_e}{\mu_r} \left( \frac{A_L}{A_L'} - 1 \right)
$$

Where
- $ A_{L}' $ : the corrected inductance factor (in nH or µH), after introducing the air gap
- $ A_L $ : the initial inductance factor provided by the core manufacturer (in nH or µH)
- $ l_g $ : the air gap length (in mm)
- $ L_e $ : the effective magnetic path length of the core (in mm)

This equation accounts for the effect of the air gap on the inductance. Increasing the air gap reduces the effective permeability, and thus reduces $ A_{L}' $.

In [9]:
dic={"core":"ELP 43/10/28 with I 43/4/28 N87",
 "Al_nH":7300, 
"Aemin":217,
"Le":61.6 ,
"µe":1560 ,
"K1":358,
"K2":-0.794,    
"K3_25":621, 
"K4_25":-0.796,
"Bsat": 300}
core ="ELP 43/10/28__AND__I 43/4/28 N87"
Aemin = dic['Aemin']
K1 = dic["K1"]
K2 = dic["K2"]
K3_25 = dic["K3_25"]
K4_25 = dic["K4_25"]
Al_nH0 = dic["Al_nH"]
Le = dic["Le"]
mu_e = dic["µe"]

In [10]:
%%render long
core
Aemin 
K1 
K2 
K3_25 
K4_25 
Al_nH0 
Le 
mu_e 
s_mm= (Al_nH/K1)**(1/K2) # mm
lg_mm= Le *(Al_nH0/Al_nH-1)/mu_e # mm
I_dc = (0.9*Al_nH/K3_25)**(1/K4_25)
B_peak = 1e3*Lm*sqrt(2)*Im_rms/(Np*Aemin*1e-6)

In [11]:
%%render
u0= 4*pi **1e-7
N=4
lg=lg_mm
le=61.6
ue=1560
Bpeak2 = 1e6*u0*N*sqrt(2)*Im_rms/(lg+le/ue)

So, the estimated air gap $s_{\mathrm{mm}}$ using the datasheet constants $K_1$ and $K_2$ is slightly greater than the calculated $l_{g\_\mathrm{mm}}$ air gap obtained from the simple formula.

In [12]:
# https://www.tdk-electronics.tdk.com/inf/80/db/fer/elp_22_6_16.pdf
# https://www.tdk-electronics.tdk.com/inf/80/db/fer/elp_32_6_20.pdf
# https://www.tdk-electronics.tdk.com/inf/80/db/fer/elp_38_8_25.pdf
# https://www.tdk-electronics.tdk.com/inf/80/db/fer/elp_43_10_28.pdf
# https://www.tdk-electronics.tdk.com/inf/80/db/fer/elp_58_11_38.pdf
# https://www.tdk-electronics.tdk.com/inf/80/db/fer/elp_64_10_50.pdf
# https://www.tdk-electronics.tdk.com/inf/80/db/fer/e_70_33_32.pdf
# https://www.tdk-electronics.tdk.com/inf/80/db/fer/e_80_38_40.pdf

In [13]:
dfcore = pd.DataFrame([
    
{"core":"ELP 43/10/28 with I 43/4/28 N87",
 "Al_nH":7300, 
"Aemin":217,
"Le":61.6 ,
"µe":1560 ,
"K1":358,
"K2":-0.794,    
#"K3_25":621, 
#"K4_25":-0.796,
"Bsat": 300}
, 

{"core":"ELP 58/11/38 with I 58/4/38 N87",
 "Al_nH":7400, 
"Aemin":308,
"Le": 80.7 ,
"µe":1540 ,
"K1":591,
"K2":-0.685, 
#"K3_25":791, 
#"K4_25":-0.796,
"Bsat": 300},



{"core":"ELP 64/10/50 with I 64/5/50 N87",
"Al_nH": 14000, 
"Aemin":518,
"Le": 69.7,
"µe": 1450, 
"K1":835,
"K2":-0.790, 
#"K3_25":1316, 
#"K4_25":-0.796, 
"Bsat":300},


    
{"core":"ELP 64/10/50 with ELP 64/10/50 N87",
 "Al_nH":12500, 
"Aemin":518,
"Le": 79,
"µe": 1490, 
"K1":820,
"K2":-0.767, 
"Bsat":300},

    
{"core":"ELP 64/10/50 with ELP 64/10/50 N95",
 "Al_nH":15500, 
"Aemin":518,
"Le": 79,
"µe": 1880, 
"Bsat":320},

{"core":"ELP 102/20/38 with I 102/7/38 N87",
 "Al_nH":9300, 
"Aemin":524.5,
"Le": 121.2,
"µe":1680 ,  
"Bsat":300
}

])

for i in range (len(dfcore)):
    dic  =dfcore.loc[i,:].to_dict()
    Aemin = dic['Aemin']
    K1 = dic["K1"]
    K2 = dic["K2"]
    #K3_25 = dic["K3_25"]
    #K4_25 = dic["K4_25"]
    Al_nH0 = dic["Al_nH"]
    Le = dic["Le"]
    µe = dic["µe"]
    s_mm= (Al_nH/K1)**(1/K2) # airgap
    lg_mm= Le *(Al_nH0/Al_nH-1)/µe
    #I_dc = (0.9*Al_nH/K3_25)**(1/K4_25)
    B_peak = 1e3*Lm*sqrt(2)*Im_rms/(Np*Aemin*1e-6)
    
    µ0= 4*pi **1e-7
    N=4
    lg = lg_mm*1e-3
    le = Le*1e-3
    Bpeak2 = µ0*N*sqrt(2)*Im_rms/(lg+le/µe)
    
    dfcore.loc[i,"s_mm"]=s_mm
    dfcore.loc[i,"lg_mm"]=lg_mm
    dfcore.loc[i,"s_div_e"]=s_mm/lg_mm
  
    dfcore.loc[i,"B_peak"]=B_peak
    dfcore.loc[i,"Bpeak2"]=Bpeak2
    #dfcore.loc[i,"Idc_25"]=I_dc
    dfcore.loc[i,"Bpeak_inf_Bsat"]=dic["Bsat"]>B_peak

In [14]:
dfcore.set_index("core")

,Al_nH,Aemin,Le,µe,K1,K2,Bsat,s_mm,lg_mm,s_div_e,B_peak,Bpeak2,Bpeak_inf_Bsat
core,,,,,,,,,,,,,
ELP 43/10/28 with I 43/4/28 N87,7300,217.0,61.6,1560,358.0,-0.794,300,0.046570,0.031043,1.500191,744.940031,2.243170e+06,False
ELP 58/11/38 with I 58/4/38 N87,7400,308.0,80.7,1540,591.0,-0.685,300,0.059428,0.042479,1.399007,524.844113,1.667464e+06,False
ELP 64/10/50 with I 64/5/50 N87,14000,518.0,69.7,1450,835.0,-0.790,300,0.133949,0.116591,1.148878,312.069472,9.608338e+05,False
ELP 64/10/50 with ELP 64/10/50 N87,12500,518.0,79.0,1490,820.0,-0.767,300,0.123167,0.109141,1.128515,312.069472,9.756415e+05,False
ELP 64/10/50 with ELP 64/10/50 N95,15500,518.0,79.0,1880,NaN,NaN,320,NaN,0.117345,NaN,312.069472,9.927506e+05,True
ELP 102/20/38 with I 102/7/38 N87,9300,524.5,121.2,1680,NaN,NaN,300,NaN,0.092019,NaN,308.202072,9.637509e+05,False

ELP 64/10/50 with ELP 64/10/50 N95 is the only choice with B_peak < B_sat 
but this solution use 2 ELP, not the optimum 
I propose to go with ELP 64/10/50 with I 64/5/50 N87
The I shape is more compact
B_peak = 312 , B_sat = 300
So there is a rsisc of saturation in low frequency, bu we will try to handle this by control.

In [15]:
dic_trans_core= dfcore[dfcore.core=="ELP 64/10/50 with I 64/5/50 N87"].iloc[0,:].to_dict()
keys = ['core', 'Al_nH', 'Aemin', 'Le', 'µe', 'Bsat', 's_mm' , 'B_peak']
dic_trans_core = {k:dic_trans_core[k] for k in keys}
dic_trans_core

{'core': 'ELP 64/10/50 with I 64/5/50 N87',
 'Al_nH': 14000,
 'Aemin': 518.0,
 'Le': 69.7,
 'µe': 1450,
 'Bsat': 300,
 's_mm': 0.1339488641172734,
 'B_peak': 312.06947242700016}

In [16]:
dfcores = pd.read_csv("FerriteCores.csv",sep=";").iloc[:,:-3]
dfcores

,core,Aemin(mm2),Le(mm),Ve(mm3),Bsat mT,Loss (W/set),K1,K2,µe,Al(nH),price by set
0,E64/10/50-3C95,519.0,79.9,40700,330.0,20.0,NaN,NaN,NaN,17000,11.05
1,ELP 43/10/28 with I 43/4/28 N87,217.0,50.8,11430,350.0,7.8,390.0,-0.784,1480.0,850,2.61
2,ELP 64/10/50 with I 64/5/50 N87,512.0,69.7,36200,300.0,4.8,835.0,-0.790,1450.0,14000,NaN
3,ELP 64/10/50 with ELP 64/10/50 N95,518.0,79.9,41500,320.0,5.1,NaN,NaN,1880.0,15500,14.52
4,ELP 64/10/50 with ELP 64/10/50 N87,518.0,79.9,41500,300.0,5.5,820.0,-0.767,1490.0,12500,11.27
5,E64/10/50 + PLT64/50/5 3C95,519.0,69.7,35500,330.0,17.0,NaN,NaN,NaN,18500,NaN
6,ER64/13/51-3C92 3C95,507.0,93.0,52600,330.0,25.0,NaN,NaN,NaN,17100,19.62
7,E100/60/28 N87,690.0,274.0,201390,NaN,4.7,NaN,NaN,1930.0,6500,17.40
8,ELP 102/20/38 with ELP 102/20/38 N87,524.5,147.6,79410,NaN,11.0,NaN,NaN,1790.0,8200,12.88
9,ELP 102/20/38 with ELP 102/20/38 N97,524.5,147.6,79410,NaN,9.7,NaN,NaN,1855.0,8500,14.07
10,ELP 102/20/38 with I 102/7/38 N97,534.2,121.2,67745,NaN,8.0,NaN,NaN,1740.0,9600,NaN
11,E 80/38/20 N95,388.0,184.0,71800,330.0,8.0,NaN,NaN,1680.0,4500,4.33

In [17]:
mask  = dfcores["Bsat mT"].isna()
dfcores.loc[mask, "Bsat mT"] = 300
dfcores.loc[9:10,"Bsat mT"]=310 # N97=310

In [18]:
arr= []
for i in range (len(dfcores)):
    dic  =dfcores.loc[i,:].to_dict()
    Aemin = dic['Aemin(mm2)']
    K1 = dic["K1"]
    K2 = dic["K2"]
    #K3_25 = dic["K3_25"]
    #K4_25 = dic["K4_25"]
    Al_nH0 = dic["Al(nH)"]
    Le = dic["Le(mm)"]
    µe = dic["µe"]
    s_mm= (Al_nH/K1)**(1/K2) # airgap
    lg_mm= Le *(Al_nH0/Al_nH-1)/µe
    #I_dc = (0.9*Al_nH/K3_25)**(1/K4_25)
    B_peak = 1e3*Lm*sqrt(2)*Im_rms/(Np*Aemin*1e-6)
    
    µ0= 4*pi **1e-7
    N=4
    lg = lg_mm*1e-3
    le = Le*1e-3
    #Bpeak2 = µ0*N*sqrt(2)*Im_rms/(lg+le/µe)
    bsat  = dic["Bsat mT"]
    if B_peak < bsat: 
        marge= 100*(bsat-B_peak)/bsat
    else : 
        marge= np.nan
    arr.append({
        'core':dic['core'], 
        "s(mm)":s_mm,
        "lg(mm)":lg_mm,
        "B_peak": B_peak,
        #"Bpeak2":Bpeak2,
        "Bsat mT":bsat,
        "Bpeak_inf_Bsat":dic["Bsat mT"]>B_peak,
        "Bsat margin %": marge
        
    })
dfres = pd.DataFrame(arr)
dfres

,core,s(mm),lg(mm),B_peak,Bsat mT,Bpeak_inf_Bsat,Bsat margin %
0,E64/10/50-3C95,NaN,NaN,311.468182,330.0,True,5.615702
1,ELP 43/10/28 with I 43/4/28 N87,0.049951,-0.027186,744.940031,350.0,False,NaN
2,ELP 64/10/50 with I 64/5/50 N87,0.133949,0.116591,315.726537,300.0,False,NaN
3,ELP 64/10/50 with ELP 64/10/50 N95,NaN,0.118682,312.069472,320.0,True,2.478290
4,ELP 64/10/50 with ELP 64/10/50 N87,0.123167,0.110384,312.069472,300.0,False,NaN
5,E64/10/50 + PLT64/50/5 3C95,NaN,NaN,311.468182,330.0,True,5.615702
6,ER64/13/51-3C92 3C95,NaN,NaN,318.840210,330.0,True,3.381754
7,E100/60/28 N87,NaN,0.083820,234.278242,300.0,True,21.907253
8,ELP 102/20/38 with ELP 102/20/38 N87,NaN,0.082983,308.202072,300.0,False,NaN
9,ELP 102/20/38 with ELP 102/20/38 N97,NaN,0.085916,308.202072,310.0,True,0.579977
10,ELP 102/20/38 with I 102/7/38 N97,NaN,0.093959,302.605741,310.0,True,2.385245
11,E 80/38/20 N95,NaN,0.011068,416.628832,330.0,False,NaN

In [19]:
dfcores2 = pd.read_csv("FerriteCores.csv", sep=";").iloc[:,:-2]
df= dfcores2.merge(dfres)
mask = df.	Bpeak_inf_Bsat
df[mask].set_index("core").T

core,E64/10/50-3C95,ELP 64/10/50 with ELP 64/10/50 N95,E64/10/50 + PLT64/50/5 3C95,ER64/13/51-3C92 3C95
Aemin(mm2),519.0,518.0,519.0,507.0
Le(mm),79.9,79.9,69.7,93.0
Ve(mm3),40700,41500,35500,52600
Bsat mT,330.0,320.0,330.0,330.0
Loss (W/set),20.0,5.1,17.0,25.0
K1,NaN,NaN,NaN,NaN
K2,NaN,NaN,NaN,NaN
µe,NaN,1880.0,NaN,NaN
Al(nH),17000,15500,18500,17100
price by set,11.05,14.52,NaN,19.62
where,digikey,mouser,NaN,digikey
s(mm),NaN,NaN,NaN,NaN
lg(mm),NaN,0.118682,NaN,NaN
B_peak,311.468182,312.069472,311.468182,318.84021
Bpeak_inf_Bsat,True,True,True,True
Bsat margin %,5.615702,2.47829,5.615702,3.381754

In [20]:
for i in range(len(dfcores)):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11

### Core ELP 64/10/50 with I 64/5/50

μ_r: relative permeability (material property)
μ_e: effective permeability (assembly/shape property)

In [ ]:
%%render long
core = "" #ELP 64/10/50 with I 64/5/50
A_e= 519 # mm2
l_e=69.7 # mm
mu_r=1450 # N87
B_sat=300 # mT @ 250A/m 10kHz 100°C
K1= 835 # @ 25°C, 0.10 mm < s < 2.00 mm
K2= -0.79 # @ 25°C, 0.10 mm < s < 2.00 mm
mu_0 = 4*pi *1e-7 # H m−1

In [ ]:
l_g= 0.11

In [ ]:
%%render 
Ae= A_e*1e-6 # m2
le=l_e*1e-3 # m
l_g = (mu_0*n**2*Ae)/Lm -le/mu_r
lg = l_g*1e3

In [ ]:
l_g= lg

In [ ]:
l_e, l_g, A_e

In [ ]:
%%render long
mu_e = (l_e+l_g)/(l_g+l_e/mu_r)
R_core = l_e/(mu_0*mu_r*A_e)
R_gap = l_g/(mu_0*A_e)
R_tot= R_core+R_gap
R_tot_2= (l_g+l_e)/(mu_0*mu_e*A_e)# Using µe

In [ ]:
%%render long
Im_sat= B_sat*Ae*(R_core+R_gap)/n # A

In [ ]:
%%render long 
Im_peak = sqrt(2)*Im_rms # A

### Verification of the Hypothesis

In [ ]:
%%render long
Vf=0.2 # drop voltage in the mos
efficiency = 0.95 # Hypothesis, efficiency= 95\%
loss = (1-efficiency)/3 # Hypothesis: Joule loss = 1/3 of total losses
Io_nom = Power/Vo_nom # A
V_loss = ((Power*loss)/efficiency)/Io_nom # v

In [ ]:
%%render long
margin = 0.01
Mg_max = n*(Vo_max*(1+margin)+Vf+V_loss)/(V_In_min/2)
# 110% load
Mg_max110 = Mg_max*(110/100)

In [ ]:
def calculate_Mg(Ln, fn, Qe):
    numerator = Ln * fn**2
    denominator_real = (Ln + 1) * fn**2 - 1
    denominator_imag = (fn**2 - 1) * fn * Qe * Ln
    denominator = np.sqrt(denominator_real**2+ denominator_imag**2)
    Mg = abs(numerator / denominator)
    return Mg
freqn = np.arange(0.5,1.8,0.01) 
Lnc=3 
Qec = 0.55 
Mg = calculate_Mg(Lnc,freqn, Qec)

i= np.argmin(np.abs(Mg-Mg_max))
fn_MgMin= freqn[i]

f_nom = 100e3 # Hz
fn_min = fsw_min/f_nom
fn_max = fsw_max/f_nom
fmin_2=fn_MgMin*f_nom
fig, ax = plt.subplots(figsize=(5, 4)) 
ax.plot(freqn, Mg,label = "Lnc=3, Qec = 0.55" , c="C9")

ax.plot([fn_min*0.8,fn_max*1.2 ], [Mg_max110, Mg_max110],
       label = "Mg_max_110%", linestyle ="--", c="k")
ax.plot([fn_min*0.8,fn_max*1.2], [Mg_max,Mg_max ],
      label = "Mg_max", linestyle ="--", c="r")



ax.plot([fn_MgMin,fn_MgMin], [0.7, 1.4],
        label = f"fn_min ({fmin_2/1e3:.2f}kHz)", linestyle ="--", c="g")


ax.set_xlabel("freq_norm")
ax.set_ylabel("Mg")

ax.legend()
ax.grid()

In [26]:
%%render long
fmin_2=fn_MgMin*f_nom
omega_min=2*pi*fmin_2
Im_rms = 2*sqrt(2)*n*Vo_nom/(pi*Lm*omega_min) # Arms
Im_peak2=sqrt(2)*Im_rms # A

I_satMargin = 100*(Im_sat-Im_peak2)/Im_sat # \%

NameError: name 'fn_MgMin' is not defined

In [ ]:
# we will shose 
# ELP 64/10/50 with ELP 64/10/50 N95

### Other cores

In [24]:
dfcores = pd.read_csv("FerriteCores.csv",sep=";").iloc[:,:-3]
dfcores

,core,Aemin(mm2),Le(mm),Ve(mm3),Bsat mT,Loss (W/set),K1,K2,µe,Al(nH),price by set
0,E64/10/50-3C95,519.0,79.9,40700,330.0,20.0,NaN,NaN,NaN,17000,11.05
1,ELP 43/10/28 with I 43/4/28 N87,217.0,50.8,11430,350.0,7.8,390.0,-0.784,1480.0,850,2.61
2,ELP 64/10/50 with I 64/5/50 N87,512.0,69.7,36200,300.0,4.8,835.0,-0.790,1450.0,14000,NaN
3,ELP 64/10/50 with ELP 64/10/50 N95,518.0,79.9,41500,320.0,5.1,NaN,NaN,1880.0,15500,14.52
4,ELP 64/10/50 with ELP 64/10/50 N87,518.0,79.9,41500,300.0,5.5,820.0,-0.767,1490.0,12500,11.27
5,E64/10/50 + PLT64/50/5 3C95,519.0,69.7,35500,330.0,17.0,NaN,NaN,NaN,18500,NaN
6,ER64/13/51-3C92 3C95,507.0,93.0,52600,330.0,25.0,NaN,NaN,NaN,17100,19.62
7,E100/60/28 N87,690.0,274.0,201390,NaN,4.7,NaN,NaN,1930.0,6500,17.40
8,ELP 102/20/38 with ELP 102/20/38 N87,524.5,147.6,79410,NaN,11.0,NaN,NaN,1790.0,8200,12.88
9,ELP 102/20/38 with ELP 102/20/38 N97,524.5,147.6,79410,NaN,9.7,NaN,NaN,1855.0,8500,14.07
10,ELP 102/20/38 with I 102/7/38 N97,534.2,121.2,67745,NaN,8.0,NaN,NaN,1740.0,9600,NaN
11,E 80/38/20 N95,388.0,184.0,71800,330.0,8.0,NaN,NaN,1680.0,4500,4.33

In [25]:
arr=[]
for i in range(len(dfcores)):
    mu_0 = 4*pi *1e-7 # H m−1 
    A_e = dfcores.loc[i, "Aemin(mm2)"]
    l_e = dfcores.loc[i, "Le(mm)"]
    B_sat = dfcores.loc[i, "Bsat mT"]
    mu_r = dfcores.loc[i, "µe"]
    #dfcores.loc[i, "Al(nH)"]
    K1 = dfcores.loc[i, "K1"]
    K2 = dfcores.loc[i, "K2"]
    core = dfcores.loc[i, "core"]


    Ae= A_e*1e-6 # m2
    le=l_e*1e-3 # m
    l_g = (mu_0*n**2*Ae)/Lm -le/mu_r
    lg = l_g*1e3
    l_g= lg
    
    
    mu_e = (l_e+l_g)/(l_g+l_e/mu_r)
    R_core = l_e/(mu_0*mu_r*A_e)
    R_gap = l_g/(mu_0*A_e)
    R_tot= R_core+R_gap
    R_tot_2= (l_g+l_e)/(mu_0*mu_e*A_e)# Using µe
    
    
    Im_sat= B_sat*Ae*(R_core+R_gap)/n # A

    arr.append({"core": core,"Im_peak": Im_peak2,  "Im_sat":Im_sat, "l_g":l_g})
pd.DataFrame(arr)

NameError: name 'Im_peak2' is not defined

## Lr design

**The input data**

In [270]:
params = ['Lr_uH', 'fsw_min', 'fsw_max', 'Ir_rms']

dic_Lr= {x:out_datas[x] for x in params}
#print("Transormer parameters:")
#display(dic_Lr)

In [278]:
%%render 
Lr_uH # µH
Ir_rms # Arms

**Relationship Between Inductance Ratio and Number of Turns**

In [279]:
pd.DataFrame(np.array([list(range(1,10)),
                       [1e3*Lr_uH/n**2 for n in range(1,10)]]).T,
            columns = ["Nb", "Al_nH"])

    Nb         Al_nH
0  1.0  21797.000000
1  2.0   5449.250000
2  3.0   2421.888889
3  4.0   1362.312500
4  5.0    871.880000
5  6.0    605.472222
6  7.0    444.836735
7  8.0    340.578125
8  9.0    269.098765

**Calculation Using the ELP 58/11/38 Core**

In [327]:
%%render long
core = "ELP 58/11/38__with __I 58/4/38 N87"
Aemin = 308 # mm2: datasheet
Al_nH0 = 8400 # nH: datasheet
Le= 67.7 # mm: datasheet
K1= 591 # datasheet
K2= -0.685 # datasheet
B_sat = 300 # mT: datasheet

n=4 # turns: 4 layers pcb

<br><br>**$B_{peak}$ and the margin**

In [328]:
%%render long
B_peak = 1e-3*Lr_uH*sqrt(2)*Ir_rms/(n*Aemin*1e-6) # mT
B_margin = 100*(B_sat-B_peak )/B_sat  # \%

**The Air Gap Calculated Using the TDK Factors K₁, K₂, and the Simple Formula**

In [332]:
%%render long
Al_nH= 1e3*Lr_uH/n**2 # nH/turn squared
s_mm= (Al_nH/K1)**(1/K2) # mm airgap 
lg_mm= Le *(Al_nH0/Al_nH-1)/µe# mm

**The cores listed below are verified, but only the ‘ELP 58/11/38’ yields a B_peak below 300 mT.**

In [298]:
t= """core,Ae_min(mm2)
ELP 22/6/16 with ELP 22/6/16,78.3 
ELP 32/6/20 with ELP 32/6/20,128
ELP 38/8/25 with ELP 38/8/25,192
ELP 43/10/28 with ELP 43/10/28,217
ELP 58/11/38 with ELP 58/11/38,308""".split("\n")
t= [x.split(",") for x in t]
df = pd.DataFrame(t[1:], columns = t[0])
Aemin = df["Ae_min(mm2)"].astype("float32")
B_peak = 1e-3*Lr_uH*sqrt(2)*Ir_rms/(n*Aemin*1e-6) # mT
df["B_peak(mT)"]=B_peak
df

                             core Ae_min(mm2)   B_peak(mT)
0    ELP 22/6/16 with ELP 22/6/16       78.3   1019.056152
1    ELP 32/6/20 with ELP 32/6/20         128   623.375732
2    ELP 38/8/25 with ELP 38/8/25         192   415.583832
3  ELP 43/10/28 with ELP 43/10/28         217   367.705536
4  ELP 58/11/38 with ELP 58/11/38         308   259.065247

https://www.tdk-electronics.tdk.com/inf/80/db/fer/elp_22_6_16.pdf<br>
https://www.tdk-electronics.tdk.com/inf/80/db/fer/elp_32_6_20.pdf<br>
https://www.tdk-electronics.tdk.com/inf/80/db/fer/elp_38_8_25.pdf<br>
https://www.tdk-electronics.tdk.com/inf/80/db/fer/elp_43_10_28.pdf<br>
https://www.tdk-electronics.tdk.com/inf/80/db/fer/elp_58_11_38.pdf